import type { Language } from '../../analysis/types';
import type { ModuleSummary } from '../../analysis/modules';

export interface TemplateInput {
  projectName: string;
  languages: Language[];
  totalFiles: number;
  modules: ModuleSummary[];
}

const LANGUAGE_LABELS: Record<Language, string> = {
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  python: 'Python',
};

/**
 * A single hardcoded CLAUDE.md template (Milestone 1 scope only — no token-budget
 * scoring, no minimal-diff patching, no confirmation queue; those come at
 * later milestones). Region markers are included so the format already matches what the
 * real marker-based compiler (build spec §5) will patch in place of later.
 */
export function buildClaudeMdTemplate(input: TemplateInput): string {
  const languageLabel = input.languages.length
    ? input.languages.map((l) => LANGUAGE_LABELS[l]).join(', ')
    : 'no Tier-1 languages detected';

  const lines: string[] = [];

  lines.push(`# ${input.projectName}`);
  lines.push('');
  lines.push('<!-- ctxkeep:start:overview -->');
  lines.push(
    `${input.projectName} is a ${languageLabel} project with ${input.totalFiles} source ` +
      `file${input.totalFiles === 1 ? '' : 's'} across ${input.modules.length} top-level module${
        input.modules.length === 1 ? '' : 's'
      }.`,
  );
  lines.push('<!-- ctxkeep:end -->');
  lines.push('');
  lines.push('<!-- ctxkeep:start:modules -->');
  lines.push('## Modules');
  lines.push('');

  if (input.modules.length === 0) {
    lines.push('_No Tier-1 source files (.ts/.tsx/.js/.py) were found._');
  } else {
    for (const mod of input.modules) {
      const langLabel = mod.languages.map((l) => LANGUAGE_LABELS[l]).join(', ');
      const sample = mod.sampleSymbols.map((s) => `\`${s.name}\``).join(', ');
      const suffix = sample ? ` — e.g. ${sample}` : '';
      lines.push(`- **${mod.name}/** — ${mod.fileCount} file${mod.fileCount === 1 ? '' : 's'} (${langLabel})${suffix}`);
    }
  }

  lines.push('<!-- ctxkeep:end -->');
  lines.push('');
  lines.push('_Generated by `ctxkeep try` — preview only; nothing was written to disk._');
  lines.push('');

  return lines.join('\n');
}
